'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DBModels
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DBModels")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Departments() As DbSet(Of Department)
    Public Overridable Property Employees() As DbSet(Of Employee)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property VacationsLogs() As DbSet(Of VacationsLog)
    Public Overridable Property VacationTypes() As DbSet(Of VacationType)

End Class
