'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property EmployeeId As Integer
    Public Property Name As String
    Public Property Position As String
    Public Property Age As Nullable(Of Integer)
    Public Property Salary As Nullable(Of Integer)
    Public Property DepartmentId As Nullable(Of Integer)

    Public Overridable Property Department As Department
    Public Overridable Property VacationsLogs As ICollection(Of VacationsLog) = New HashSet(Of VacationsLog)

End Class
