'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VacationsLog
    Public Property VacationId As Integer
    Public Property EmployeeId As Nullable(Of Integer)
    Public Property VacationCode As Nullable(Of Integer)
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)

    Public Overridable Property Employee As Employee
    Public Overridable Property VacationType As VacationType

End Class
